#ifndef __CONFIG_APPS_H_
#define __CONFIG_APPS_H_
#define INCLUDE_ECHO_SERVER    1
#define INCLUDE_WEB_SERVER     1
#define INCLUDE_TFTP_SERVER    1
#define INCLUDE_RXPERF_SERVER  1
#define INCLUDE_TXPERF_CLIENT  1
#define INCLUDE_TXUPERF_CLIENT 0
#define INCLUDE_RXUPERF_CLIENT 0
#endif
