# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/OneDrive/GitHub/webserver_sdsoc_2016_3/constraints/target_pins.xdc

# Block Designs: bd/sd_accel/sd_accel.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_accel || ORIG_REF_NAME==sd_accel}]

# IP: bd/sd_accel/ip/sd_accel_axi_gpio_0_0/sd_accel_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_accel_axi_gpio_0_0 || ORIG_REF_NAME==sd_accel_axi_gpio_0_0}]

# IP: bd/sd_accel/ip/sd_accel_ocl_block_0_0/sd_accel_ocl_block_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_accel_ocl_block_0_0 || ORIG_REF_NAME==sd_accel_ocl_block_0_0}]

# IP: bd/sd_accel/ip/sd_accel_processing_system7_0_0/sd_accel_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_accel_processing_system7_0_0 || ORIG_REF_NAME==sd_accel_processing_system7_0_0}]

# IP: bd/sd_accel/ip/sd_accel_ps7_0_axi_periph_0/sd_accel_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_accel_ps7_0_axi_periph_0 || ORIG_REF_NAME==sd_accel_ps7_0_axi_periph_0}]

# IP: bd/sd_accel/ip/sd_accel_xbar_0/sd_accel_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_accel_xbar_0 || ORIG_REF_NAME==sd_accel_xbar_0}]

# IP: bd/sd_accel/ip/sd_accel_rst_ps7_0_100M_0/sd_accel_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_accel_rst_ps7_0_100M_0 || ORIG_REF_NAME==sd_accel_rst_ps7_0_100M_0}]

# IP: bd/sd_accel/ip/sd_accel_xlconcat_0_0/sd_accel_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_accel_xlconcat_0_0 || ORIG_REF_NAME==sd_accel_xlconcat_0_0}]

# IP: bd/sd_accel/ip/sd_accel_zed_audio_ctrl_0_0/sd_accel_zed_audio_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_accel_zed_audio_ctrl_0_0 || ORIG_REF_NAME==sd_accel_zed_audio_ctrl_0_0}]

# IP: bd/sd_accel/ip/sd_accel_auto_pc_0/sd_accel_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_accel_auto_pc_0 || ORIG_REF_NAME==sd_accel_auto_pc_0}]

# IP: bd/sd_accel/ip/sd_accel_auto_pc_1/sd_accel_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sd_accel_auto_pc_1 || ORIG_REF_NAME==sd_accel_auto_pc_1}]

# XDC: bd/sd_accel/sd_accel_ooc.xdc
