# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.cache/wt [current_project]
set_property parent.project_path D:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths d:/OneDrive/GitHub/webserver_sdsoc_2016_3/ip_lib [current_project]
set_property ip_output_repo d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/hdl/sd_accel_wrapper.vhd
add_files D:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/sd_accel.bd
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_axi_gpio_0_0/sd_accel_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_axi_gpio_0_0/sd_accel_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_axi_gpio_0_0/sd_accel_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_3/bd_4831_sys_reset_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_3/bd_4831_sys_reset_0.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_3/bd_4831_sys_reset_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_4/constraints/addone_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_1/bd_4831_s00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/bd_4831_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/sd_accel_ocl_block_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_processing_system7_0_0/sd_accel_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_xbar_0/sd_accel_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_rst_ps7_0_100M_0/sd_accel_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_rst_ps7_0_100M_0/sd_accel_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_rst_ps7_0_100M_0/sd_accel_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_auto_pc_0/sd_accel_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_auto_pc_1/sd_accel_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/sd_accel_ooc.xdc]
set_property is_locked true [get_files D:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/sd_accel.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/OneDrive/GitHub/webserver_sdsoc_2016_3/constraints/target_pins.xdc
set_property used_in_implementation false [get_files D:/OneDrive/GitHub/webserver_sdsoc_2016_3/constraints/target_pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top sd_accel_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef sd_accel_wrapper.dcp

catch { report_utilization -file sd_accel_wrapper_utilization_synth.rpt -pb sd_accel_wrapper_utilization_synth.pb }
