# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Sim/2016_3_zed_source/lab7/zed_audio/hw/vivado/zed_audio.srcs/sources_1/bd/zed_audio/ip/zed_audio_axi_gpio_0_0/zed_audio_axi_gpio_0_0.xci
# IP: The module: 'zed_audio_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Sim/2016_3_zed_source/lab7/zed_audio/hw/vivado/zed_audio.srcs/sources_1/bd/zed_audio/ip/zed_audio_axi_gpio_0_0/zed_audio_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_audio_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Sim/2016_3_zed_source/lab7/zed_audio/hw/vivado/zed_audio.srcs/sources_1/bd/zed_audio/ip/zed_audio_axi_gpio_0_0/zed_audio_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_audio_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Sim/2016_3_zed_source/lab7/zed_audio/hw/vivado/zed_audio.srcs/sources_1/bd/zed_audio/ip/zed_audio_axi_gpio_0_0/zed_audio_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_audio_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Sim/2016_3_zed_source/lab7/zed_audio/hw/vivado/zed_audio.srcs/sources_1/bd/zed_audio/ip/zed_audio_axi_gpio_0_0/zed_audio_axi_gpio_0_0.xci
# IP: The module: 'zed_audio_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Sim/2016_3_zed_source/lab7/zed_audio/hw/vivado/zed_audio.srcs/sources_1/bd/zed_audio/ip/zed_audio_axi_gpio_0_0/zed_audio_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_audio_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Sim/2016_3_zed_source/lab7/zed_audio/hw/vivado/zed_audio.srcs/sources_1/bd/zed_audio/ip/zed_audio_axi_gpio_0_0/zed_audio_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_audio_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Sim/2016_3_zed_source/lab7/zed_audio/hw/vivado/zed_audio.srcs/sources_1/bd/zed_audio/ip/zed_audio_axi_gpio_0_0/zed_audio_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_audio_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
