# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/sd_accel_ocl_block_0_0.xci
# IP: The module: 'sd_accel_ocl_block_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/bd_4831.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831 || ORIG_REF_NAME==bd_4831}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_0/bd_4831_m_axi_interconnect_M_AXI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_m_axi_interconnect_M_AXI_0 || ORIG_REF_NAME==bd_4831_m_axi_interconnect_M_AXI_0}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_2/bd_4831_s_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_s_axi_interconnect_0_0 || ORIG_REF_NAME==bd_4831_s_axi_interconnect_0_0}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_3/bd_4831_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_sys_reset_0 || ORIG_REF_NAME==bd_4831_sys_reset_0}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_4/bd_4831_kernel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_kernel_0_0 || ORIG_REF_NAME==bd_4831_kernel_0_0}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_5/bd_4831_slave_bridge_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_slave_bridge_0 || ORIG_REF_NAME==bd_4831_slave_bridge_0}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_6/bd_4831_master_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_master_bridge_0_0 || ORIG_REF_NAME==bd_4831_master_bridge_0_0}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_1/bd_4831_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_s00_regslice_0 || ORIG_REF_NAME==bd_4831_s00_regslice_0}]

# XDC: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/bd_4831_ooc.xdc

# XDC: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/sd_accel_ocl_block_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sd_accel_ocl_block_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/sd_accel_ocl_block_0_0.xci
# IP: The module: 'sd_accel_ocl_block_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/bd_4831.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831 || ORIG_REF_NAME==bd_4831}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_0/bd_4831_m_axi_interconnect_M_AXI_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_m_axi_interconnect_M_AXI_0 || ORIG_REF_NAME==bd_4831_m_axi_interconnect_M_AXI_0}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_2/bd_4831_s_axi_interconnect_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_s_axi_interconnect_0_0 || ORIG_REF_NAME==bd_4831_s_axi_interconnect_0_0}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_3/bd_4831_sys_reset_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_sys_reset_0 || ORIG_REF_NAME==bd_4831_sys_reset_0}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_4/bd_4831_kernel_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_kernel_0_0 || ORIG_REF_NAME==bd_4831_kernel_0_0}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_5/bd_4831_slave_bridge_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_slave_bridge_0 || ORIG_REF_NAME==bd_4831_slave_bridge_0}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_6/bd_4831_master_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_master_bridge_0_0 || ORIG_REF_NAME==bd_4831_master_bridge_0_0}]

# IP: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_1/bd_4831_s00_regslice_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_4831_s00_regslice_0 || ORIG_REF_NAME==bd_4831_s00_regslice_0}]

# XDC: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/bd_4831_ooc.xdc

# XDC: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/sd_accel_ocl_block_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sd_accel_ocl_block_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
