# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/target_pins.xdc

# XDC: imports/constraints/_i_bitgen_common.xdc

# XDC: imports/constraints/_i_SC0701_TE0720.xdc

# XDC: imports/constraints/_i_TE0720-SC.xdc

# XDC: imports/constraints/_i_unused_io.xdc

# Block Designs: bd/zynq_soc/zynq_soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc || ORIG_REF_NAME==zynq_soc}]

# IP: bd/zynq_soc/ip/zynq_soc_DIP_SWITCHES_8BITS_0/zynq_soc_DIP_SWITCHES_8BITS_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_DIP_SWITCHES_8BITS_0 || ORIG_REF_NAME==zynq_soc_DIP_SWITCHES_8BITS_0}]

# IP: bd/zynq_soc/ip/zynq_soc_LEDS_8BITS_0/zynq_soc_LEDS_8BITS_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_LEDS_8BITS_0 || ORIG_REF_NAME==zynq_soc_LEDS_8BITS_0}]

# IP: bd/zynq_soc/ip/zynq_soc_PUSH_BUTTONS_POSITION_0/zynq_soc_PUSH_BUTTONS_POSITION_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_PUSH_BUTTONS_POSITION_0 || ORIG_REF_NAME==zynq_soc_PUSH_BUTTONS_POSITION_0}]

# IP: bd/zynq_soc/ip/zynq_soc_Sine_0/zynq_soc_Sine_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_Sine_0 || ORIG_REF_NAME==zynq_soc_Sine_0}]

# IP: bd/zynq_soc/ip/zynq_soc_processing_system7_0_0/zynq_soc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_processing_system7_0_0 || ORIG_REF_NAME==zynq_soc_processing_system7_0_0}]

# IP: bd/zynq_soc/ip/zynq_soc_ps7_0_axi_periph_1/zynq_soc_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_ps7_0_axi_periph_1 || ORIG_REF_NAME==zynq_soc_ps7_0_axi_periph_1}]

# IP: bd/zynq_soc/ip/zynq_soc_rst_ps7_0_100M_0/zynq_soc_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_soc_rst_ps7_0_100M_0}]

# IP: bd/zynq_soc/ip/zynq_soc_xbar_1/zynq_soc_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_xbar_1 || ORIG_REF_NAME==zynq_soc_xbar_1}]

# IP: bd/zynq_soc/ip/zynq_soc_auto_pc_1/zynq_soc_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_auto_pc_1 || ORIG_REF_NAME==zynq_soc_auto_pc_1}]

# XDC: bd/zynq_soc/zynq_soc_ooc.xdc
