// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xaddone.h"

extern XAddone_Config XAddone_ConfigTable[];

XAddone_Config *XAddone_LookupConfig(u16 DeviceId) {
	XAddone_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XADDONE_NUM_INSTANCES; Index++) {
		if (XAddone_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XAddone_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XAddone_Initialize(XAddone *InstancePtr, u16 DeviceId) {
	XAddone_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XAddone_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XAddone_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

