// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XADDONE_H
#define XADDONE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xaddone_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XAddone_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XAddone;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XAddone_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XAddone_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XAddone_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XAddone_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XAddone_Initialize(XAddone *InstancePtr, u16 DeviceId);
XAddone_Config* XAddone_LookupConfig(u16 DeviceId);
int XAddone_CfgInitialize(XAddone *InstancePtr, XAddone_Config *ConfigPtr);
#else
int XAddone_Initialize(XAddone *InstancePtr, const char* InstanceName);
int XAddone_Release(XAddone *InstancePtr);
#endif

void XAddone_Start(XAddone *InstancePtr);
u32 XAddone_IsDone(XAddone *InstancePtr);
u32 XAddone_IsIdle(XAddone *InstancePtr);
u32 XAddone_IsReady(XAddone *InstancePtr);
void XAddone_EnableAutoRestart(XAddone *InstancePtr);
void XAddone_DisableAutoRestart(XAddone *InstancePtr);

void XAddone_Set_a(XAddone *InstancePtr, u32 Data);
u32 XAddone_Get_a(XAddone *InstancePtr);
void XAddone_Set_b(XAddone *InstancePtr, u32 Data);
u32 XAddone_Get_b(XAddone *InstancePtr);
void XAddone_Set_elements(XAddone *InstancePtr, u32 Data);
u32 XAddone_Get_elements(XAddone *InstancePtr);

void XAddone_InterruptGlobalEnable(XAddone *InstancePtr);
void XAddone_InterruptGlobalDisable(XAddone *InstancePtr);
void XAddone_InterruptEnable(XAddone *InstancePtr, u32 Mask);
void XAddone_InterruptDisable(XAddone *InstancePtr, u32 Mask);
void XAddone_InterruptClear(XAddone *InstancePtr, u32 Mask);
u32 XAddone_InterruptGetEnabled(XAddone *InstancePtr);
u32 XAddone_InterruptGetStatus(XAddone *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
