// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xaddone.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAddone_CfgInitialize(XAddone *InstancePtr, XAddone_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAddone_Start(XAddone *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAddone_ReadReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_AP_CTRL) & 0x80;
    XAddone_WriteReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XAddone_IsDone(XAddone *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAddone_ReadReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XAddone_IsIdle(XAddone *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAddone_ReadReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XAddone_IsReady(XAddone *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAddone_ReadReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XAddone_EnableAutoRestart(XAddone *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAddone_WriteReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XAddone_DisableAutoRestart(XAddone *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAddone_WriteReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_AP_CTRL, 0);
}

void XAddone_Set_a(XAddone *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAddone_WriteReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_A_DATA, Data);
}

u32 XAddone_Get_a(XAddone *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAddone_ReadReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_A_DATA);
    return Data;
}

void XAddone_Set_b(XAddone *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAddone_WriteReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_B_DATA, Data);
}

u32 XAddone_Get_b(XAddone *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAddone_ReadReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_B_DATA);
    return Data;
}

void XAddone_Set_elements(XAddone *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAddone_WriteReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_ELEMENTS_DATA, Data);
}

u32 XAddone_Get_elements(XAddone *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAddone_ReadReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_ELEMENTS_DATA);
    return Data;
}

void XAddone_InterruptGlobalEnable(XAddone *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAddone_WriteReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_GIE, 1);
}

void XAddone_InterruptGlobalDisable(XAddone *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAddone_WriteReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_GIE, 0);
}

void XAddone_InterruptEnable(XAddone *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAddone_ReadReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_IER);
    XAddone_WriteReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_IER, Register | Mask);
}

void XAddone_InterruptDisable(XAddone *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAddone_ReadReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_IER);
    XAddone_WriteReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_IER, Register & (~Mask));
}

void XAddone_InterruptClear(XAddone *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAddone_WriteReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_ISR, Mask);
}

u32 XAddone_InterruptGetEnabled(XAddone *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAddone_ReadReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_IER);
}

u32 XAddone_InterruptGetStatus(XAddone *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAddone_ReadReg(InstancePtr->Control_BaseAddress, XADDONE_CONTROL_ADDR_ISR);
}

