# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/vivado/zed_audio.xdc

# Block Designs: bd/zed_audio/zed_audio.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_audio || ORIG_REF_NAME==zed_audio}]

# IP: bd/zed_audio/ip/zed_audio_processing_system7_0_0/zed_audio_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_audio_processing_system7_0_0 || ORIG_REF_NAME==zed_audio_processing_system7_0_0}]

# IP: bd/zed_audio/ip/zed_audio_axi_gpio_0_0/zed_audio_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_audio_axi_gpio_0_0 || ORIG_REF_NAME==zed_audio_axi_gpio_0_0}]

# IP: bd/zed_audio/ip/zed_audio_zed_audio_ctrl_0_0/zed_audio_zed_audio_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_audio_zed_audio_ctrl_0_0 || ORIG_REF_NAME==zed_audio_zed_audio_ctrl_0_0}]

# IP: bd/zed_audio/ip/zed_audio_ps7_0_axi_periph_0/zed_audio_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_audio_ps7_0_axi_periph_0 || ORIG_REF_NAME==zed_audio_ps7_0_axi_periph_0}]

# IP: bd/zed_audio/ip/zed_audio_rst_ps7_0_100M_0/zed_audio_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_audio_rst_ps7_0_100M_0 || ORIG_REF_NAME==zed_audio_rst_ps7_0_100M_0}]

# IP: bd/zed_audio/ip/zed_audio_xbar_0/zed_audio_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_audio_xbar_0 || ORIG_REF_NAME==zed_audio_xbar_0}]

# IP: bd/zed_audio/ip/zed_audio_xlconcat_0_0/zed_audio_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_audio_xlconcat_0_0 || ORIG_REF_NAME==zed_audio_xlconcat_0_0}]

# IP: bd/zed_audio/ip/zed_audio_auto_pc_0/zed_audio_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zed_audio_auto_pc_0 || ORIG_REF_NAME==zed_audio_auto_pc_0}]

# XDC: bd/zed_audio/zed_audio_ooc.xdc
