# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_4/constraints/addone_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4831_kernel_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/OneDrive/GitHub/webserver_sdsoc_2016_3/hw/vivado/webserver_sdsoc_2016_3.srcs/sources_1/bd/sd_accel/ip/sd_accel_ocl_block_0_0/bd_0/ip/ip_4/constraints/addone_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_4831_kernel_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
