# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/constraints/target_pins.xdc

# XDC: D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/constraints/_i_bitgen_common.xdc

# XDC: D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/constraints/_i_SC0701_TE0720.xdc

# XDC: D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/constraints/_i_TE0720-SC.xdc

# XDC: D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/constraints/_i_unused_io.xdc

# Block Designs: bd/zynq_soc/zynq_soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc || ORIG_REF_NAME==zynq_soc}]

# IP: bd/zynq_soc/ip/zynq_soc_DIP_SWITCHES_8BITS_0/zynq_soc_DIP_SWITCHES_8BITS_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_DIP_SWITCHES_8BITS_0 || ORIG_REF_NAME==zynq_soc_DIP_SWITCHES_8BITS_0}]

# IP: bd/zynq_soc/ip/zynq_soc_LEDS_8BITS_0/zynq_soc_LEDS_8BITS_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_LEDS_8BITS_0 || ORIG_REF_NAME==zynq_soc_LEDS_8BITS_0}]

# IP: bd/zynq_soc/ip/zynq_soc_PUSH_BUTTONS_POSITION_0/zynq_soc_PUSH_BUTTONS_POSITION_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_PUSH_BUTTONS_POSITION_0 || ORIG_REF_NAME==zynq_soc_PUSH_BUTTONS_POSITION_0}]

# IP: bd/zynq_soc/ip/zynq_soc_Sine_0/zynq_soc_Sine_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_Sine_0 || ORIG_REF_NAME==zynq_soc_Sine_0}]

# IP: bd/zynq_soc/ip/zynq_soc_processing_system7_0_0/zynq_soc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_processing_system7_0_0 || ORIG_REF_NAME==zynq_soc_processing_system7_0_0}]

# IP: bd/zynq_soc/ip/zynq_soc_ps7_0_axi_periph_0/zynq_soc_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_soc_ps7_0_axi_periph_0}]

# IP: bd/zynq_soc/ip/zynq_soc_xbar_0/zynq_soc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_xbar_0 || ORIG_REF_NAME==zynq_soc_xbar_0}]

# IP: bd/zynq_soc/ip/zynq_soc_rst_ps7_0_50M_0/zynq_soc_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_soc_rst_ps7_0_50M_0}]

# IP: bd/zynq_soc/ip/zynq_soc_auto_pc_0/zynq_soc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_auto_pc_0 || ORIG_REF_NAME==zynq_soc_auto_pc_0}]

# XDC: bd/zynq_soc/zynq_soc_ooc.xdc
