# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.cache/wt [current_project]
set_property parent.project_path D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/ip_lib [current_project]
set_property ip_output_repo d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/hdl/zynq_soc_wrapper.vhd
add_files D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/zynq_soc.bd
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_DIP_SWITCHES_8BITS_0/zynq_soc_DIP_SWITCHES_8BITS_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_DIP_SWITCHES_8BITS_0/zynq_soc_DIP_SWITCHES_8BITS_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_DIP_SWITCHES_8BITS_0/zynq_soc_DIP_SWITCHES_8BITS_0.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_LEDS_8BITS_0/zynq_soc_LEDS_8BITS_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_LEDS_8BITS_0/zynq_soc_LEDS_8BITS_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_LEDS_8BITS_0/zynq_soc_LEDS_8BITS_0.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_PUSH_BUTTONS_POSITION_0/zynq_soc_PUSH_BUTTONS_POSITION_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_PUSH_BUTTONS_POSITION_0/zynq_soc_PUSH_BUTTONS_POSITION_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_PUSH_BUTTONS_POSITION_0/zynq_soc_PUSH_BUTTONS_POSITION_0.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_processing_system7_0_0/zynq_soc_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_xbar_0/zynq_soc_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_rst_ps7_0_50M_0/zynq_soc_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_rst_ps7_0_50M_0/zynq_soc_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_rst_ps7_0_50M_0/zynq_soc_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_pc_0/zynq_soc_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/zynq_soc_ooc.xdc]
set_property is_locked true [get_files D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/vivado/webserver/webserver_sdsoc_2016_3.srcs/sources_1/bd/zynq_soc/zynq_soc.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/constraints/target_pins.xdc
set_property used_in_implementation false [get_files D:/GITHUB_EXTERNAL/webserver_sdsoc_2016_3/constraints/target_pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top zynq_soc_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef zynq_soc_wrapper.dcp

catch { report_utilization -file zynq_soc_wrapper_utilization_synth.rpt -pb zynq_soc_wrapper_utilization_synth.pb }
